# Use the README file as a reference to customize settings.

CelloveNotification:
  fields:
    default: sender_id, receiver_id, notifiable_id, seen
    form: sender_id, receiver_id, notifiable_id, seen
  relationships:
  application: Application
