# Use the README file as a reference to customize settings.

City:
  fields:
    default: country, name, region, latitude, longitude
    form: country, name, region, latitude, longitude
  relationships: 
  application: Application
  search: name
