# Use the README file as a reference to customize settings.

Picture:
  fields:
    default: image, attachable_id, main
    form: image, attachable_id, main
  order_by: -created_at
  relationships: 
  application: Application
  options:
    default_action_on_item: show
    form_rows: 48
    per_page: 48
