# Use the README file as a reference to customize settings.

Picture:
  fields:
    default: image, attachable_id, main
    form: image, attachable_id, main, created_at
  order_by: -created_at
  relationships: 
  application: Application
