# Use the README file as a reference to customize settings.

Recommendation:
  fields:
    default: user_id, creator_id, relationship, description, confirmed, denied
    form: user_id, creator_id, relationship, description, confirmed, denied
  relationships: notifications, characteristic
  application: Application
