development:
  adapter: mysql2
  encoding: utf8
  database: cellove_development
  pool: 5
  host: 127.0.0.1
  username: <%= ENV.fetch('CELLOVE_MYSQL_DEV_USER', 'root')%>
  password: '<%= ENV.fetch('CELLOVE_MYSQL_DEV_PASS', 'root') %>'

test:
  adapter: mysql2
  encoding: utf8
  database: cellove_test
  pool: 5
  username: <%= ENV.fetch('CELLOVE_MYSQL_TEST_USER', 'root')%>
  host: 127.0.0.1
  password: '<%= ENV.fetch('CELLOVE_MYSQL_TEST_PASS', 'root') %>'

staging:
  adapter: mysql2
  encoding: utf8
  database: cellove_staging
  pool: 5
  host: 127.0.0.1
  username: cellove
  password: '12345'

production:
  adapter: mysql2
  encoding: utf8
  database: cellove_production
  pool: 5
  host: 127.0.0.1
  username: cellove
  password: '12345'

mobile:
  adapter: mysql2
  encoding: utf8
  database: cellove_mobile
  pool: 5
  host: 127.0.0.1
  username: cellove
  password: '12345'