development:
  adapter: mysql2
  encoding: utf8
  database: cellove_development
  pool: 5
  user: root
  host: 127.0.0.1

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: cellove_development
  pool: 5
  user: root
  host: 127.0.0.1
